# Generated by Django 5.2.1 on 2025-11-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('mpesa', '0001_initial'), ('mpesa', '0002_alter_mpesatransaction_result_code')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaB2CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100, unique=True)),
                ('originator_conversation_id', models.CharField(max_length=100)),
                ('response_code', models.CharField(max_length=10)),
                ('response_description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=14)),
                ('command_id', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('occasion', models.CharField(max_length=255)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_completed_date', models.CharField(blank=True, max_length=20, null=True)),
                ('b2c_utility_account_available_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('b2c_working_account_available_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('b2c_charges_paid_account_available_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('receiver_party_public_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=50)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('payment_type', models.CharField(choices=[('product', 'Product'), ('subscription', 'Subscription')], default='product', max_length=20)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('subscription_plan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('account_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_desc', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
