# Generated by Django 5.0.4 on 2024-10-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_transaction_id', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('party_id_type', models.CharField(max_length=50)),
                ('party_id', models.CharField(max_length=255)),
                ('payer_message', models.TextField(blank=True)),
                ('payee_note', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('party_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('party_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_message', models.TextField(blank=True, null=True)),
                ('payee_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('financial_transaction_id', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('party_id_type', models.CharField(max_length=50)),
                ('party_id', models.CharField(max_length=255)),
                ('payer_message', models.TextField(blank=True)),
                ('payee_note', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(blank=True, null=True)),
                ('ref', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('financial_transaction_id', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=100)),
                ('party_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('party_id', models.CharField(max_length=50)),
                ('payer_message', models.CharField(blank=True, max_length=100, null=True)),
                ('payee_note', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
