# Generated by Django 5.2.7 on 2025-11-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayHeroWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=150, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayHeroTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Internal unique reference', max_length=120, unique=True)),
                ('provider_txn_id', models.CharField(blank=True, help_text='ID returned by PayHero/provider', max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, help_text='e.g. m-pesa, sasapay, intasend', max_length=40, null=True)),
                ('channel_id', models.IntegerField(blank=True, help_text='Wallet/payment channel identifier used', null=True)),
                ('operation_type', models.CharField(blank=True, help_text='payment | topup | withdraw | global', max_length=30, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('pending', 'Pending'), ('processing', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_status_payload', models.JSONField(blank=True, default=dict, help_text='Most recent raw status response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['reference'], name='payhero_pay_referen_d4c1c9_idx'), models.Index(fields=['provider_txn_id'], name='payhero_pay_provide_147e90_idx')],
            },
        ),
    ]
